"""empty message

Revision ID: 0417d352838b
Revises: 2c466b5289e6
Create Date: 2021-09-15 12:16:46.431709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0417d352838b'
down_revision = '2c466b5289e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
