"""empty message

Revision ID: 2233d161b995
Revises: da47e4913abb
Create Date: 2021-09-15 19:23:11.745385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2233d161b995'
down_revision = 'da47e4913abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=200), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
