"""empty message

Revision ID: 2c466b5289e6
Revises: c05d283c5c91
Create Date: 2021-09-15 11:18:53.492046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c466b5289e6'
down_revision = 'c05d283c5c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###
