"""empty message

Revision ID: 2f20d677f047
Revises: 3a4a385cd900
Create Date: 2021-09-13 21:02:19.149813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f20d677f047'
down_revision = '3a4a385cd900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'group_id')
    op.alter_column('events', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
