"""empty message

Revision ID: 31cb92f17304
Revises: c034795fb94c
Create Date: 2021-09-16 01:10:56.263201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cb92f17304'
down_revision = 'c034795fb94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.add_column('events', sa.Column('status', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'events', ['status'])
    op.drop_constraint(u'events_status_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'status_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'events_status_id_fkey', 'events', 'status', ['status_id'], ['id'])
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_column('events', 'status')
    op.create_table('status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'status_pkey'),
    sa.UniqueConstraint('status', name=u'status_status_key')
    )
    # ### end Alembic commands ###
