"""empty message

Revision ID: 3a4a385cd900
Revises: 8226b508e1ec
Create Date: 2021-09-13 17:25:07.505862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a4a385cd900'
down_revision = '8226b508e1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['status_id'], [u'status.id'], name=u'events_status_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'events_pkey')
    )
    op.create_table('status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'status_pkey'),
    sa.UniqueConstraint('status', name=u'status_status_key')
    )
    # ### end Alembic commands ###
