"""empty message

Revision ID: 7693d5bbdfa6
Revises: e399d0a44d05
Create Date: 2021-09-15 14:29:05.481774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7693d5bbdfa6'
down_revision = 'e399d0a44d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('biography', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'author_pkey'),
    sa.UniqueConstraint('biography', name=u'author_biography_key'),
    sa.UniqueConstraint('first_name', name=u'author_first_name_key'),
    sa.UniqueConstraint('last_name', name=u'author_last_name_key')
    )
    # ### end Alembic commands ###
