"""empty message

Revision ID: 7c7d5ec03974
Revises: f4d8d50cd6e5
Create Date: 2021-09-20 13:14:10.120104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7d5ec03974'
down_revision = 'f4d8d50cd6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('event_authors',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('authors_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authors_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'authors_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
