"""empty message

Revision ID: 8226b508e1ec
Revises: 
Create Date: 2021-09-13 13:49:12.624794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8226b508e1ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Status',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Status_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Status_pkey'),
    sa.UniqueConstraint('status', name=u'Status_status_key')
    )
    # ### end Alembic commands ###
