"""empty message

Revision ID: a380a5417c99
Revises: 660184f723b8
Create Date: 2021-09-16 14:24:49.274945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a380a5417c99'
down_revision = '660184f723b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creator', sa.String(length=50), nullable=True))
    op.drop_constraint(u'events_status_key', 'events', type_='unique')
    op.create_unique_constraint(None, 'events', ['creator'])
    op.drop_column('events', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='unique')
    op.create_unique_constraint(u'events_status_key', 'events', ['status'])
    op.drop_column('events', 'creator')
    # ### end Alembic commands ###
