"""empty message

Revision ID: c05d283c5c91
Revises: e51d987e43c4
Create Date: 2021-09-14 19:33:11.393355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05d283c5c91'
down_revision = 'e51d987e43c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_constraint(u'user_public_id_key', 'user', type_='unique')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'user_public_id_key', 'user', ['public_id'])
    op.alter_column('user', 'password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
