"""empty message

Revision ID: da47e4913abb
Revises: 7693d5bbdfa6
Create Date: 2021-09-15 17:10:20.233377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da47e4913abb'
down_revision = '7693d5bbdfa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
