"""empty message

Revision ID: e399d0a44d05
Revises: 0417d352838b
Create Date: 2021-09-15 14:26:25.043686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e399d0a44d05'
down_revision = '0417d352838b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_author',
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('events_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [u'author.id'], name=u'event_author_author_id_fkey'),
    sa.ForeignKeyConstraint(['events_id'], [u'events.id'], name=u'event_author_events_id_fkey')
    )
    # ### end Alembic commands ###
