"""empty message

Revision ID: e51d987e43c4
Revises: 2f20d677f047
Create Date: 2021-09-13 23:22:39.094383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51d987e43c4'
down_revision = '2f20d677f047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event',
    sa.Column('events_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['events_id'], [u'events.id'], name=u'user_event_events_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'user_event_user_id_fkey')
    )
    # ### end Alembic commands ###
