"""empty message

Revision ID: f20ddf781d53
Revises: a380a5417c99
Create Date: 2021-09-16 16:06:54.127187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20ddf781d53'
down_revision = 'a380a5417c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'events_creator_key', 'events', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'events_creator_key', 'events', ['creator'])
    # ### end Alembic commands ###
