"""empty message

Revision ID: f4d8d50cd6e5
Revises: f20ddf781d53
Create Date: 2021-09-16 18:23:13.964532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d8d50cd6e5'
down_revision = 'f20ddf781d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party', 'register')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('register', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
